### ISSUE TITLE
ValueError: Unknown layer:name

### ISSUE THREAD

**Issue by a919224757** [michael1788/virtual_libraries#1]
python do_data_generation.py
Using TensorFlow backend.
Sampling from model saved at epoch 10
Traceback (most recent call last):
  File "do_data_generation.py", line 137, in <module>
    model = load_model(model_path)
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/engine/saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/engine/saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/engine/sequential.py", line 292, in from_config
    custom_objects=custom_objects)
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/mingyang/anaconda3/envs/mollib/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:name

I guess the software versions are different than the 2.2.0 described in the YML file

**Comment by michael1788** [comment]
I'm so sorry, that's a really late answer—for some reasons I did not see a notification for this.
Anyway, it should be the right version. Is model_path pointing toward the pretrained model of this repo, or is it your own? 
Otherwise, have you try to update to 2.2.4? Maybe this will work for you (https://github.com/keras-team/keras/issues/11617)
